<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "media_nmcad"
 *
 * Auto generated by Extension Builder 2018-01-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Media_NMCAD',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Nathan Malifarge, Matthieu Cormelier, Antoine Dethier',
    'author_email' => 'nathan.malifarge@etu.u-bordeaux.fr, matthieu.cormelier@etu.u-bordeaux.fr, antoine.dethier@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
